server:
  port: 8090
  servlet:
    context-path:
spring:
  jackson:
    serialization:
      INDENT_OUT: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authjwt
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
